import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialPostgresMigration1790621307081 implements MigrationInterface {
    name = 'InitialPostgresMigration1790621307081'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // uuid_generate_v4() (used as the default for every primary key
        // below) is provided by this extension, not built into Postgres.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletAddress" character varying NOT NULL, "nonce" character varying, "nonceExpiresAt" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, "role" text NOT NULL DEFAULT 'USER', "displayName" character varying(100), "email" character varying(255), "emailVerified" boolean NOT NULL DEFAULT false, "avatarUrl" character varying(500), "bio" text, "preferredAsset" character varying(20) NOT NULL DEFAULT 'XLM', "kycStatus" character varying NOT NULL DEFAULT 'not_started', "kycRejectionReason" character varying, "kycVerifiedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fc71cd6fb73f95244b23e2ef113" UNIQUE ("walletAddress"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "token" character varying NOT NULL, "email" character varying(255), "expiresAt" TIMESTAMP NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_595be4c36e66b21d3fd14c73a24" UNIQUE ("token"), CONSTRAINT "PK_c1ea2921e767f83cd44c0af203f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "escrow_parties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "escrowId" uuid NOT NULL, "userId" uuid NOT NULL, "role" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "respondedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005489df59d3d446c1d10ac608f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_escrow_parties_escrow_role" ON "escrow_parties" ("escrowId", "role") `);
        await queryRunner.query(`CREATE INDEX "idx_escrow_parties_user_role" ON "escrow_parties" ("userId", "role") `);
        await queryRunner.query(`CREATE TABLE "escrow_conditions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "escrowId" uuid NOT NULL, "description" text NOT NULL, "type" character varying NOT NULL DEFAULT 'manual', "isFulfilled" boolean NOT NULL DEFAULT false, "fulfilledAt" TIMESTAMP WITH TIME ZONE, "fulfilledByUserId" character varying, "fulfillmentNotes" text, "fulfillmentEvidence" text, "isMet" boolean NOT NULL DEFAULT false, "metAt" TIMESTAMP WITH TIME ZONE, "metByUserId" character varying, "metadata" text, "amount" numeric(18,7), "proposedAmount" numeric(18,7), "proposedDescription" text, "proposedByUserId" character varying, "isReleased" boolean NOT NULL DEFAULT false, "releasedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4095b69dc99498a715bfa4d90d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "escrow_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "escrowId" uuid NOT NULL, "eventType" character varying NOT NULL, "actorId" character varying, "data" text, "ipAddress" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "cursor" BIGSERIAL NOT NULL, CONSTRAINT "PK_e4a1edcfed4c7f4f57bcfb7b800" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ae1646573c6d1fe40961aa552" ON "escrow_events" ("cursor") `);
        await queryRunner.query(`CREATE TABLE "escrows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "amount" numeric(18,7) NOT NULL, "releasedAmount" numeric(18,7) NOT NULL DEFAULT '0', "asset_code" character varying NOT NULL DEFAULT 'XLM', "asset_issuer" character varying, "status" character varying NOT NULL DEFAULT 'pending', "type" character varying NOT NULL DEFAULT 'standard', "creatorId" uuid NOT NULL, "releaseTransactionHash" character varying, "stellarTxHash" character varying, "chainEscrowId" character varying, "fundedAt" TIMESTAMP WITH TIME ZONE, "on_chain_id" character varying, "isReleased" boolean NOT NULL DEFAULT false, "expiresAt" TIMESTAMP WITH TIME ZONE, "expirationNotifiedAt" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, "metadataHash" character varying, "ipfs_cid" character varying, "ipfs_metadata_hash" character varying, "ipfs_version" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9cd10ae5b52350c3a20d124f5d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_escrows_chainEscrowId" ON "escrows" ("chainEscrowId") `);
        await queryRunner.query(`CREATE INDEX "idx_escrows_creator_status_created" ON "escrows" ("creatorId", "status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_escrows_expires_at" ON "escrows" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "idx_escrows_created_at" ON "escrows" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_escrows_asset" ON "escrows" ("asset_code", "asset_issuer") `);
        await queryRunner.query(`CREATE INDEX "idx_escrows_status" ON "escrows" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_escrows_creator" ON "escrows" ("creatorId") `);
        await queryRunner.query(`CREATE TABLE "escrow_creation_intents" ("id" character varying(80) NOT NULL, "creatorId" character varying NOT NULL, "sourceAddress" character varying NOT NULL, "chainEscrowId" character varying NOT NULL, "payload" text NOT NULL, "unsignedXdr" text NOT NULL, "transactionHash" character varying, "escrowId" character varying, "status" character varying NOT NULL DEFAULT 'prepared', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_30e81eb62f1684412c1cbf78858" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "soroban_tx_intents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "escrowId" character varying NOT NULL, "on_chain_escrow_id" character varying NOT NULL, "userId" character varying NOT NULL, "operation" character varying NOT NULL, "source_account" character varying NOT NULL, "network_passphrase" character varying NOT NULL, "contract_id" character varying NOT NULL, "intent_hash" character varying NOT NULL, "unsigned_xdr" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "fee_stroops" bigint, "resource_fee_stroops" bigint, "simulated_at_ledger" bigint, "signed_xdr_hash" character varying, "txHash" character varying, "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4d69d2d3b8bd2b681df1939581e" UNIQUE ("intent_hash"), CONSTRAINT "PK_080adfaae963c0c9ecc8b30e9f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_soroban_intents_status_expires" ON "soroban_tx_intents" ("status", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_soroban_intents_user" ON "soroban_tx_intents" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_soroban_intents_escrow" ON "soroban_tx_intents" ("escrowId") `);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "escrowId" uuid NOT NULL, "filedByUserId" uuid NOT NULL, "reason" text NOT NULL, "evidence" text, "evidenceFiles" text DEFAULT '[]', "status" character varying NOT NULL DEFAULT 'open', "resolvedByUserId" uuid, "resolutionNotes" text, "sellerPercent" numeric(5,2), "buyerPercent" numeric(5,2), "outcome" character varying, "resolvedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_05cc0a36ac22b4dc8a82211d2e" UNIQUE ("escrowId"), CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_eventtype_enum" AS ENUM('PARTY_INVITED', 'PARTY_ACCEPTED', 'PARTY_REJECTED', 'ESCROW_CREATED', 'ESCROW_FUNDED', 'MILESTONE_RELEASED', 'ESCROW_COMPLETED', 'ESCROW_CANCELLED', 'DISPUTE_RAISED', 'DISPUTE_RESOLVED', 'ESCROW_EXPIRED', 'CONDITION_FULFILLED', 'CONDITION_CONFIRMED', 'EXPIRATION_WARNING')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_status_enum" AS ENUM('pending', 'sent', 'failed')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "escrowId" character varying, "eventType" "public"."notification_eventtype_enum" NOT NULL, "payload" text NOT NULL, "status" "public"."notification_status_enum" NOT NULL DEFAULT 'pending', "retryCount" integer NOT NULL DEFAULT '0', "readAt" TIMESTAMP WITH TIME ZONE, "idempotencyKey" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d5d21ddb049fe238cea9d33a9f" ON "notification" ("idempotencyKey") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_preference_channel_enum" AS ENUM('email', 'webhook')`);
        await queryRunner.query(`CREATE TABLE "notification_preference" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "channel" "public"."notification_preference_channel_enum" NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "eventTypes" text NOT NULL, "soundEnabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba8d816b10f3dcfcd2e71ce5776" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "api_key" ("id" character varying NOT NULL, "userId" character varying NOT NULL, "name" character varying NOT NULL, "keyHash" character varying NOT NULL, "keyPrefix" character varying NOT NULL, "scopes" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "revokedAt" TIMESTAMP, "rateLimitPerMinute" integer NOT NULL DEFAULT '200', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4aacb7c1641a74534c8a96c4dc9" UNIQUE ("keyHash"), CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin_audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorId" character varying(64) NOT NULL, "actionType" character varying(64) NOT NULL, "resourceType" character varying(64) NOT NULL, "resourceId" character varying(128), "metadata" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9425be48a9c753f5753017c61b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "secret" character varying NOT NULL, "events" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, CONSTRAINT "PK_9e8795cfc899ab7bdaa831e8527" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_delivery_status_enum" AS ENUM('pending', 'delivered', 'retrying', 'failed', 'dead_lettered')`);
        await queryRunner.query(`CREATE TABLE "webhook_delivery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "webhookId" uuid NOT NULL, "event" character varying NOT NULL, "payload" text NOT NULL, "status" "public"."webhook_delivery_status_enum" NOT NULL DEFAULT 'pending', "attempt" integer NOT NULL DEFAULT '1', "maxAttempts" integer NOT NULL DEFAULT '5', "nextRetryAt" TIMESTAMP WITH TIME ZONE, "lastStatusCode" integer, "lastError" text, "lastAttemptAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b1ae290239a778f12399db91354" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4295dd9d2471968d3948ecac36" ON "webhook_delivery" ("status", "nextRetryAt") `);
        await queryRunner.query(`CREATE TABLE "webhook_dead_letter" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "webhookId" uuid NOT NULL, "originalDeliveryId" character varying, "event" character varying NOT NULL, "payload" text NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "lastStatusCode" integer, "lastError" text, "failedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "replayedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cef6863dc14c71e36c434875fe6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_179c6394f32eade339285e76d9" ON "webhook_dead_letter" ("webhookId") `);
        await queryRunner.query(`CREATE TYPE "public"."stellar_events_eventtype_enum" AS ENUM('ESCROW_CREATED', 'ESCROW_FUNDED', 'MILESTONE_RELEASED', 'ESCROW_COMPLETED', 'ESCROW_CANCELLED', 'DISPUTE_CREATED', 'DISPUTE_RESOLVED')`);
        await queryRunner.query(`CREATE TABLE "stellar_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "txHash" character varying(64) NOT NULL, "eventIndex" integer NOT NULL, "eventType" "public"."stellar_events_eventtype_enum" NOT NULL, "escrowId" character varying, "ledger" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "rawPayload" text NOT NULL, "extractedFields" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "amount" numeric(18,7), "asset_code" character varying, "asset_issuer" character varying, "milestoneIndex" integer, "fromAddress" character varying, "toAddress" character varying, "reason" text, "cursor" bigint NOT NULL, CONSTRAINT "UQ_c6a70c31de4c4d3b23e6229c515" UNIQUE ("txHash", "eventIndex"), CONSTRAINT "PK_efc7a4a026a14f41246b55d7873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_33bcf3b402d8757d22c1cc1ad3" ON "stellar_events" ("txHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_56e937f62e6766e06118ae9b6c" ON "stellar_events" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad3aa47d032fd93d4f307d30ab" ON "stellar_events" ("ledger") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8d00fffa3b5110edf867481dd" ON "stellar_events" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_76c23f799c12f938f6adf6d36b" ON "stellar_events" ("cursor") `);
        await queryRunner.query(`CREATE TABLE "allowed_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(12) NOT NULL, "issuer" character varying(56), "displayName" character varying NOT NULL, "iconUrl" character varying, "decimals" integer NOT NULL DEFAULT '7', "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_05a28eb0715e2d7f5adca9c9fca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."email_outbox_status_enum" AS ENUM('pending', 'sent', 'failed')`);
        await queryRunner.query(`CREATE TABLE "email_outbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "to" character varying NOT NULL, "subject" character varying NOT NULL, "html" text NOT NULL, "text" text, "status" "public"."email_outbox_status_enum" NOT NULL DEFAULT 'pending', "attempts" integer NOT NULL DEFAULT '0', "nextRetryAt" TIMESTAMP WITH TIME ZONE, "lastError" text, "sentAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b6fbfc201f705fbf1ac87bd7197" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_email_outbox_status_retry" ON "email_outbox" ("status", "nextRetryAt") `);
        await queryRunner.query(`CREATE TABLE "backup_record" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying(256) NOT NULL, "localPath" character varying(512), "remotePath" character varying(1024), "sizeBytes" bigint NOT NULL, "status" character varying(32) NOT NULL, "backupType" character varying(32) NOT NULL, "retentionPolicy" character varying(32) NOT NULL DEFAULT 'daily', "encrypted" boolean NOT NULL DEFAULT false, "checksum" character varying(128), "metadata" text, "restoreTestStatus" character varying(32), "errorMessage" character varying(512), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a2d36e4ea5bad8682367c6ca2dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kyc_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" character varying NOT NULL DEFAULT 'mock', "providerVerificationId" character varying, "status" character varying NOT NULL DEFAULT 'pending', "rejectionReason" character varying, "providerMetadata" text, "initiatedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57b7c6b141dd225ce5dc95d7fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_kyc_provider_status" ON "kyc_verifications" ("provider", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_kyc_user" ON "kyc_verifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "escrow_chain_ids" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "network" character varying(32) NOT NULL, "contract_id" character varying(56) NOT NULL, "escrow_id" character varying(36) NOT NULL, "on_chain_id" character varying(20), "status" character varying(16) NOT NULL DEFAULT 'unmapped', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_escrow_chain_scope_chain_id" UNIQUE ("network", "contract_id", "on_chain_id"), CONSTRAINT "uq_escrow_chain_scope_escrow" UNIQUE ("network", "contract_id", "escrow_id"), CONSTRAINT "PK_8296ba37387a120798ed359f30d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_escrow_chain_lookup" ON "escrow_chain_ids" ("network", "contract_id", "on_chain_id") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verifications" ADD CONSTRAINT "FK_4e63a91e0a684b31496bd50733e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_parties" ADD CONSTRAINT "FK_0836b727fe2d2baa3fa6fefabf1" FOREIGN KEY ("escrowId") REFERENCES "escrows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_parties" ADD CONSTRAINT "FK_116f30d6ab9b41f91aad18f113f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_conditions" ADD CONSTRAINT "FK_88456ecac834c788fc912233e05" FOREIGN KEY ("escrowId") REFERENCES "escrows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_events" ADD CONSTRAINT "FK_47c8aeca9e22cd1ac03731c3305" FOREIGN KEY ("escrowId") REFERENCES "escrows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrows" ADD CONSTRAINT "FK_b483b9f73c28476240bbc993d0b" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_05cc0a36ac22b4dc8a82211d2ee" FOREIGN KEY ("escrowId") REFERENCES "escrows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_23f126d4aaaa9d67243895b784b" FOREIGN KEY ("filedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_a2215614b176b851d3e431de9b9" FOREIGN KEY ("resolvedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "FK_7dbbb3fa9d7ccab4925a67af414" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_delivery" ADD CONSTRAINT "FK_756f07a5beb3326ea1488192d89" FOREIGN KEY ("webhookId") REFERENCES "webhooks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_dead_letter" ADD CONSTRAINT "FK_179c6394f32eade339285e76d9a" FOREIGN KEY ("webhookId") REFERENCES "webhooks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_verifications" ADD CONSTRAINT "FK_f71e34495dae27087b5773b35b4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "kyc_verifications" DROP CONSTRAINT "FK_f71e34495dae27087b5773b35b4"`);
        await queryRunner.query(`ALTER TABLE "webhook_dead_letter" DROP CONSTRAINT "FK_179c6394f32eade339285e76d9a"`);
        await queryRunner.query(`ALTER TABLE "webhook_delivery" DROP CONSTRAINT "FK_756f07a5beb3326ea1488192d89"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "FK_7dbbb3fa9d7ccab4925a67af414"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_a2215614b176b851d3e431de9b9"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_23f126d4aaaa9d67243895b784b"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_05cc0a36ac22b4dc8a82211d2ee"`);
        await queryRunner.query(`ALTER TABLE "escrows" DROP CONSTRAINT "FK_b483b9f73c28476240bbc993d0b"`);
        await queryRunner.query(`ALTER TABLE "escrow_events" DROP CONSTRAINT "FK_47c8aeca9e22cd1ac03731c3305"`);
        await queryRunner.query(`ALTER TABLE "escrow_conditions" DROP CONSTRAINT "FK_88456ecac834c788fc912233e05"`);
        await queryRunner.query(`ALTER TABLE "escrow_parties" DROP CONSTRAINT "FK_116f30d6ab9b41f91aad18f113f"`);
        await queryRunner.query(`ALTER TABLE "escrow_parties" DROP CONSTRAINT "FK_0836b727fe2d2baa3fa6fefabf1"`);
        await queryRunner.query(`ALTER TABLE "email_verifications" DROP CONSTRAINT "FK_4e63a91e0a684b31496bd50733e"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrow_chain_lookup"`);
        await queryRunner.query(`DROP TABLE "escrow_chain_ids"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kyc_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kyc_provider_status"`);
        await queryRunner.query(`DROP TABLE "kyc_verifications"`);
        await queryRunner.query(`DROP TABLE "backup_record"`);
        await queryRunner.query(`DROP INDEX "public"."idx_email_outbox_status_retry"`);
        await queryRunner.query(`DROP TABLE "email_outbox"`);
        await queryRunner.query(`DROP TYPE "public"."email_outbox_status_enum"`);
        await queryRunner.query(`DROP TABLE "allowed_assets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76c23f799c12f938f6adf6d36b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8d00fffa3b5110edf867481dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad3aa47d032fd93d4f307d30ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56e937f62e6766e06118ae9b6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33bcf3b402d8757d22c1cc1ad3"`);
        await queryRunner.query(`DROP TABLE "stellar_events"`);
        await queryRunner.query(`DROP TYPE "public"."stellar_events_eventtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_179c6394f32eade339285e76d9"`);
        await queryRunner.query(`DROP TABLE "webhook_dead_letter"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4295dd9d2471968d3948ecac36"`);
        await queryRunner.query(`DROP TABLE "webhook_delivery"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_delivery_status_enum"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
        await queryRunner.query(`DROP TABLE "admin_audit_log"`);
        await queryRunner.query(`DROP TABLE "api_key"`);
        await queryRunner.query(`DROP TABLE "notification_preference"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preference_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5d21ddb049fe238cea9d33a9f"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_eventtype_enum"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP INDEX "public"."idx_soroban_intents_escrow"`);
        await queryRunner.query(`DROP INDEX "public"."idx_soroban_intents_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_soroban_intents_status_expires"`);
        await queryRunner.query(`DROP TABLE "soroban_tx_intents"`);
        await queryRunner.query(`DROP TABLE "escrow_creation_intents"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrows_creator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrows_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrows_asset"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrows_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrows_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrows_creator_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_escrows_chainEscrowId"`);
        await queryRunner.query(`DROP TABLE "escrows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ae1646573c6d1fe40961aa552"`);
        await queryRunner.query(`DROP TABLE "escrow_events"`);
        await queryRunner.query(`DROP TABLE "escrow_conditions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrow_parties_user_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_escrow_parties_escrow_role"`);
        await queryRunner.query(`DROP TABLE "escrow_parties"`);
        await queryRunner.query(`DROP TABLE "email_verifications"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
